# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_auto_20161026_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('interests', models.ManyToManyField(to='events.Interest')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid1, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='subscriber',
            name='token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.Token'),
        ),
    ]
