# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
